export interface listaResidentesI{
    id:string|number;
    nombreResidente:string;
    apellidoResidente:string;
    dniResidente:string;
    fechaNacimiento:string;
    edad:string;
    genero:string;
    medicoDeCabecera:string;
    grupoSanguineo:string;
    numeroDeHabitacion:string;
    observacionesResidente:string;
    localidadFamiliar:string;
    domicilioFamiliar:string;
    nombreFamiliar:string;
    apellidoFamiliar:string;
    numeroTelefonico:string;
    dniFamiliar:string;
    numeroAfiliado:string;
    obraSocial:string;
    vinculoConElResidente:string;
    fotoResidente:string;
}