export interface loadResidentesI{
    id?:string|number|null|undefined;
    nombreResidente?:string|null|undefined;
    apellidoResidente?:string|null|undefined;
    dniResidente?:string|null|undefined;
    fechaNacimiento?:string|null|undefined;
    edad?:string|null|undefined;
    genero?:string|null|undefined;
    medicoDeCabecera?:string|null|undefined;
    grupoSanguineo?:string|null|undefined;
    numeroDeHabitacion?:string|null|undefined;
    observacionesResidente?:string|null|undefined;
    localidadFamiliar?:string|null|undefined;
    domicilioFamiliar?:string|null|undefined;
    nombreFamiliar?:string|null|undefined;
    apellidoFamiliar?:string|null|undefined;
    numeroTelefonico?:string|null|undefined;
    dniFamiliar?:string|null|undefined;
    numeroAfiliado?:string|null|undefined;
    obraSocial?:string|null|undefined;
    vinculoConElResidente?:string|null|undefined;
    fotoResidente?:string;
}